### ISSUE TITLE
compile error on Xcode 13

### ISSUE THREAD

**Issue by irvingdp** [alice-biometrics/onboarding-react-native#16]
Dear team,
I try build AppOnboardingSample on Xcode 13 but get compile error.

Environment:
- 	node v14.18.0
- 	xcode 13.2.1
- 	swift 5.5.2

Steps To Reproduce
1. 	npm install
2. 	cd ios & pod install
3. 	open AppOnboardingSample.xcworkspace by xcode
4. 	build with iphone 11 simulator

Expected Results
Expect Xcode project to compile, link and build correctly.
	
Actual Results
<img width="1571" alt="截圖 2022-01-26 上午12 42 37" src="https://user-images.githubusercontent.com/3470002/151021236-8f8a9e5a-b687-4e1f-929b-9008f82b0ad1.png">

**Comment by irvingdp** [comment]
also complie failed on android
![截圖 2022-01-26 下午3 17 02](https://user-images.githubusercontent.com/3470002/151119682-c4c36c78-9e5a-4f9b-9999-56f3e15bb658.png)

**Comment by miguel-lorenzo** [comment]
Hio @irvingdp 

We have just released a [new version](https://github.com/alice-biometrics/onboarding-react-native/releases/tag/v1.10.5) that should fix your compilation errors.

Please have a try and let us know if everything is ok.

Regards.
