### ISSUE TITLE
android build fail: More than one file was found with OS independent path 'lib/x86/libc++_shared.so'

### ISSUE THREAD

**Issue by irvingdp** [alice-biometrics/onboarding-react-native#17]
Dear team,
The version v1.10.5 build by gradle but failed, below is error message.

> cd android & ./gradlew assembleDebug
![截圖 2022-01-28 下午3 00 46](https://user-images.githubusercontent.com/3470002/151502206-35a7f275-81c2-4093-bbc8-b309d1281de4.png)

> cd android & ./gradlew assembleRelease
![截圖 2022-01-28 下午2 40 01](https://user-images.githubusercontent.com/3470002/151500688-e6548b12-41e5-4053-b97e-c7a854c4654a.png)

**Comment by miguel-lorenzo** [comment]
Hi Ivan,

Could you try adding the following to your `build.gradle`?

```
android {
    packagingOptions {
        pickFirst '**/libc++_shared.so'
    }
```

This should make it work.

Regards
