### ISSUE TITLE
After clicking the 'continue' button, the onboarding component did not exit until the second click.

### ISSUE THREAD

**Issue by irvingdp** [alice-biometrics/onboarding-react-native#20]
We encountered a UI issue.
After completing the selfie and document verification, pressing the 'continue' button did not exit the onboarding component until the second click.

This video indicates the issue.
https://drive.google.com/file/d/1N859tZkLP99l08MnWRTWDKJ2RmJ1ZFw4/view?usp=sharing

version: 2.2.3
platform: ios

**Comment by miguel-lorenzo** [comment]
Hi @irvingdp,

For these kind of questions, please head up to [our support channel](https://alicebiometrics.freshdesk.com/support/login), where we will be happy to assist you.

Regards.
